# Generated by Django 4.2.8 on 2025-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_userprofile_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='budget',
        ),
        migrations.AddField(
            model_name='destination',
            name='budget_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='budget_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='season',
            field=models.CharField(blank=True, choices=[('Winter', 'Зима'), ('Spring', 'Весна'), ('Summer', 'Лето'), ('Autumn', 'Осень'), ('All', 'Круглый год')], max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='activity_type',
            field=models.CharField(choices=[('Skiing', 'Горнолыжный'), ('Cultural', 'Культурный'), ('Beach', 'Пляжный'), ('Gastronomic', 'Гастрономический'), ('Ecotourism', 'Экотуризм'), ('Shopping', 'Шопинг')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate',
            field=models.CharField(choices=[('Tropical', 'Тропический'), ('Subtropical', 'Субтропический'), ('Temperate', 'Умеренный'), ('Continental', 'Континентальный'), ('Arctic', 'Арктический')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='cultural_diversity',
            field=models.CharField(choices=[('Museums', 'Музеи и история'), ('Festivals', 'Фестивали и события'), ('Modern', 'Современная культура')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='popularity',
            field=models.CharField(choices=[('Quiet', 'Спокойный'), ('Moderate', 'Средний'), ('Busy', 'Оживлённый')], max_length=30),
        ),
    ]
