# Generated by Django 4.2.8 on 2025-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_remove_destination_budget_destination_budget_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='comfort_level',
            field=models.CharField(blank=True, choices=[('Бюджетный', 'Бюджетный'), ('Средний', 'Средний'), ('Люкс', 'Люкс')], max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='family_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='language',
            field=models.CharField(blank=True, choices=[('Английский', 'Английский'), ('Русский', 'Русский'), ('Местный язык', 'Местный язык'), ('Другое', 'Другое')], max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='transport',
            field=models.CharField(blank=True, choices=[('Прямой авиаперелёт', 'Прямой авиаперелёт'), ('Поезд', 'Поезд'), ('Автобус', 'Автобус'), ('С пересадкой', 'С пересадкой')], max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='visa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='activity_type',
            field=models.CharField(choices=[('Горнолыжное', 'Горнолыжный'), ('Культурный', 'Культурный'), ('Пляжный', 'Пляжный'), ('Гастрономический', 'Гастрономический'), ('Экотуризм', 'Экотуризм'), ('Шопинг', 'Шопинг'), ('Приключенческий', 'Приключенческий')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate',
            field=models.CharField(choices=[('Тропический', 'Тропический'), ('Субтропический', 'Субтропический'), ('Умеренный', 'Умеренный'), ('Континентальный', 'Континентальный'), ('Арктический', 'Арктический')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='cultural_diversity',
            field=models.CharField(choices=[('Музеи и история', 'Музеи и история'), ('Фестивали и события', 'Фестивали и события'), ('Современная культура', 'Современная культура')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='popularity',
            field=models.CharField(choices=[('Спокойная', 'Спокойная'), ('Средняя', 'Средняя'), ('Оживлённая', 'Оживлённая')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='season',
            field=models.CharField(blank=True, choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень'), ('Круглый год', 'Круглый год')], max_length=50),
        ),
    ]
