# Generated by Django 4.2.8 on 2025-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_destination_comfort_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activity_type',
            field=models.CharField(choices=[('Горнолыжный', 'Горнолыжный'), ('Культурный', 'Культурный'), ('Пляжный', 'Пляжный'), ('Гастрономический', 'Гастрономический'), ('Экотуризм', 'Экотуризм'), ('Шопинг', 'Шопинг'), ('Приключенческий', 'Приключенческий')], max_length=30),
        ),
    ]
