# Generated by Django 4.2.8 on 2025-05-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0009_alter_destination_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters_hash', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination')),
            ],
        ),
    ]
