# Generated by Django 4.2.8 on 2025-05-14 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0010_relevancescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
