# Generated by Django 4.2.8 on 2025-05-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0011_destination_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='embedding',
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Просмотр'), ('favorite', 'Избранное'), ('review', 'Отзыв'), ('search', 'Поиск')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_filters', models.JSONField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
