# Generated by Django 4.2.8 on 2025-05-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0012_remove_destination_embedding_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination'),
        ),
    ]
