# Generated by Django 4.2.8 on 2025-05-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0013_alter_userinteraction_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='cultural_diversity',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='transport',
        ),
        migrations.AddField(
            model_name='destination',
            name='vibe',
            field=models.CharField(blank=True, choices=[('Европейская классика', 'Европейская классика'), ('Современный мегаполис', 'Современный мегаполис'), ('Азиатская культура', 'Азиатская культура'), ('Средневековая архитектура', 'Средневековая архитектура'), ('Восточная экзотика', 'Восточная экзотика'), ('Деревенский уют', 'Деревенский уют'), ('Горы и природа', 'Горы и природа'), ('Морской курорт', 'Морской курорт'), ('Пустыня и приключения', 'Пустыня и приключения')], max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate',
            field=models.CharField(choices=[('Жаркий и сухой', 'Жаркий и сухой'), ('Жаркий и влажный', 'Жаркий и влажный'), ('Тёплый и умеренный', 'Тёплый и умеренный'), ('Прохладный и свежий', 'Прохладный и свежий'), ('Пасмурный и дождливый', 'Пасмурный и дождливый'), ('Холодный и снежный', 'Холодный и снежный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='season',
            field=models.CharField(blank=True, choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], max_length=50),
        ),
    ]
