# Generated by Django 4.2.8 on 2025-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0014_remove_destination_budget_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Горнолыжный', 'Горнолыжный'), ('Культурный', 'Культурный'), ('Пляжный', 'Пляжный'), ('Гастрономический', 'Гастрономический'), ('Экотуризм', 'Экотуризм'), ('Шопинг', 'Шопинг'), ('Приключенческий', 'Приключенческий')], max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='language',
            field=models.CharField(blank=True, choices=[('Английский', 'Английский'), ('Русский', 'Русский'), ('Французский', 'Французский'), ('Немецкий', 'Немецкий'), ('Испанский', 'Испанский'), ('Итальянский', 'Итальянский'), ('Португальский', 'Португальский'), ('Арабский', 'Арабский'), ('Китайский', 'Китайский'), ('Японский', 'Японский'), ('Другое', 'Другое')], max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='activity_types',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel_app.activitytype'),
        ),
    ]
