# Generated by Django 4.2.8 on 2025-05-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0016_auto_20250530_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='activity_type',
        ),
    ]
