# Generated by Django 4.2.8 on 2025-05-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0017_remove_destination_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Бюджетный', 'Бюджетный'), ('Средний', 'Средний'), ('Люкс', 'Люкс')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Английский', 'Английский'), ('Русский', 'Русский'), ('Французский', 'Французский'), ('Немецкий', 'Немецкий'), ('Испанский', 'Испанский'), ('Итальянский', 'Итальянский'), ('Португальский', 'Португальский'), ('Арабский', 'Арабский'), ('Китайский', 'Китайский'), ('Японский', 'Японский'), ('Другое', 'Другое')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Романтика', 'Романтика'), ('Активный отдых', 'Активный отдых'), ('Природа', 'Природа'), ('Городской отдых', 'Городской отдых'), ('Релакс', 'Релакс')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Европейская классика', 'Европейская классика'), ('Современный мегаполис', 'Современный мегаполис'), ('Азиатская культура', 'Азиатская культура'), ('Средневековая архитектура', 'Средневековая архитектура'), ('Восточная экзотика', 'Восточная экзотика'), ('Деревенский уют', 'Деревенский уют'), ('Горы и природа', 'Горы и природа'), ('Морской курорт', 'Морской курорт'), ('Пустыня и приключения', 'Пустыня и приключения')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='additional_image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='comfort_level',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='language',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='vibe',
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_additional_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='travel_app.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='comfort_level',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel_app.comfortlevel'),
        ),
        migrations.AddField(
            model_name='destination',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel_app.language'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel_app.tag'),
        ),
        migrations.AddField(
            model_name='destination',
            name='vibe',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='travel_app.vibe'),
        ),
    ]
