# Generated by Django 4.2.8 on 2025-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0019_inspirationpost_delete_relevancescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='travel_app.inspirationpost'),
        ),
    ]
