# Generated by Django 4.2.8 on 2025-06-07 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0020_userprofile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspirationpost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='inspirationpost',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='inspirationpost',
            name='new_place_city',
        ),
        migrations.RemoveField(
            model_name='inspirationpost',
            name='new_place_country',
        ),
        migrations.RemoveField(
            model_name='inspirationpost',
            name='new_place_name',
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PendingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inspirationpost',
            name='pending_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='travel_app.pendingdestination'),
        ),
    ]
