# Generated by Django 4.2.8 on 2025-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0021_remove_inspirationpost_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='inspiration_posts', to='travel_app.tag'),
        ),
        migrations.AddField(
            model_name='inspirationpost',
            name='vibe',
            field=models.ManyToManyField(blank=True, related_name='inspiration_posts', to='travel_app.vibe'),
        ),
        migrations.AddField(
            model_name='pendingdestination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pending_destinations', to='travel_app.tag'),
        ),
        migrations.AddField(
            model_name='pendingdestination',
            name='vibe',
            field=models.ManyToManyField(blank=True, related_name='pending_destinations', to='travel_app.vibe'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.inspirationpost'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='post_filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Просмотр места'), ('favorite', 'Избранное'), ('review', 'Отзыв'), ('search', 'Поиск'), ('view_post', 'Просмотр поста')], max_length=20),
        ),
    ]
