# Generated by Django 4.2.8 on 2025-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0022_inspirationpost_tags_inspirationpost_vibe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_inspiration_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='travel_app.inspirationpost'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Просмотр места'), ('favorite', 'Избранное'), ('review', 'Отзыв'), ('search', 'Поиск'), ('view_post', 'Просмотр поста'), ('save_post', 'Сохранение поста')], max_length=20),
        ),
    ]
