# Generated by Django 4.2.8 on 2025-06-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0023_userprofile_saved_inspiration_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination'),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration_images/'),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='pending_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.pendingdestination'),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travel_app.tag'),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='vibe',
            field=models.ManyToManyField(blank=True, to='travel_app.vibe'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Просмотр места'), ('favorite', 'Избранное'), ('review', 'Отзыв'), ('search', 'Поиск'), ('view_post', 'Просмотр поста'), ('save_post', 'Сохранение поста'), ('like_post', 'Лайк поста')], max_length=20),
        ),
    ]
