# Generated by Django 4.2.8 on 2025-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0024_inspirationpost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdestination',
            name='climate',
            field=models.CharField(blank=True, choices=[('Жаркий и сухой', 'Жаркий и сухой'), ('Жаркий и влажный', 'Жаркий и влажный'), ('Тёплый и умеренный', 'Тёплый и умеренный'), ('Прохладный и свежий', 'Прохладный и свежий'), ('Пасмурный и дождливый', 'Пасмурный и дождливый'), ('Холодный и снежный', 'Холодный и снежный')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pendingdestination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pendingdestination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_destination_images/'),
        ),
        migrations.AddField(
            model_name='pendingdestination',
            name='season',
            field=models.CharField(blank=True, choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingdestination',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingdestination',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travel_app.tag'),
        ),
        migrations.AlterField(
            model_name='pendingdestination',
            name='vibe',
            field=models.ManyToManyField(blank=True, to='travel_app.vibe'),
        ),
    ]
