# Generated by Django 4.2.8 on 2025-06-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0025_pendingdestination_climate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdestination',
            name='description',
            field=models.TextField(),
        ),
    ]
