# Generated by Django 4.2.8 on 2025-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0027_route_routepoint_userprofile_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='routepoint',
            name='image',
        ),
        migrations.AddField(
            model_name='routepoint',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
